In [1]:
import torch
import numpy as np

In [2]:
# Creating tensors - this can be done with regular lists or transferred from numpy
a = [11, 33, 323]
b = np.array([44, 55, 66], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(t_a)
print(t_b)

tensor([ 11,  33, 323])
tensor([44, 55, 66], dtype=torch.int32)


In [3]:
# It is possible to use inbuilts to create tensors full of ones or zeros
# or random entries
t_ones = torch.ones(size=(2, 3))
print(t_ones.shape)
print(t_ones)

rand_tensor = torch.rand(size=(2, 3))
print(rand_tensor)

torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.1524, 0.3442, 0.8729],
        [0.6637, 0.5759, 0.2637]])


In [4]:
# Change datatypes as needed
t_a_new = t_a.to(dtype=torch.int64)
print(t_a_new.dtype)

torch.int64


In [5]:
# We can change the tensorial dimensions as needed
t = torch.rand(3, 5)
print('Original')
print(t.shape)

# Transposing
t_tr = torch.transpose(t, 0, 1) # Swaps dim0 = 0 and dim1 = 1
print('Transpose along dimensions 0 and 1')
print(t_tr.shape)

# Forcefully reshape
t_reshape = t.reshape(1, 15)
print('Reshaped to 1 row and 15 columns')
print(t_reshape.shape)

# Remove unnecessary dimensions (i.e. dimensions that have size 1)
t = torch.zeros(1, 2, 1, 3, 1)
# Squeeze only dimension indexed 2. dim=None will squeeze out all dimensions of size 1
t_squeeze = torch.squeeze(t, dim=2)

print('Original shape:', t.shape, '-> Squeezed shape:', t_squeeze.shape)

Original
torch.Size([3, 5])
Transpose along dimensions 0 and 1
torch.Size([5, 3])
Reshaped to 1 row and 15 columns
torch.Size([1, 15])
Original shape: torch.Size([1, 2, 1, 3, 1]) -> Squeezed shape: torch.Size([1, 2, 3, 1])


In [6]:
# Mathematical operations
torch.manual_seed(42)

# Scalar multiplication and element-wise subtraction
t1 = 2 * torch.rand(4, 3) - 1

# Create a normally distributed random tensor
t2 = torch.normal(mean=0, std=1, size=(4, 3))

# Hadamard (element-wise) multiplication
t3 = torch.multiply(t1, t2)
print("hadamard(t1, t2)")
print(t3)

# Descriptive stats along an axis
t4 = torch.mean(t1, axis=0)
print("\nRow-wise mean of t1")
print(t4)
print("Row-wise standard deviation of t1")
t5 = torch.std(t1, axis=0)
print(t5)

# Matrix multiplication 4 x 3 and 3 x 4 should produce a 4 x 4 (transposing t2 creates a 3 x 4)
t6 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print("\nt1 . t2^T")
print(t6)
# Similarly we can do a 3 x 4  by 4 x 3
t7 = torch.matmul(torch.transpose(t1, 0, 1), t2)
print("\nt1^T . t2")
print(t7)

# Norms: L_p norm 
# ord <-> p, dim <-> axis
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
print("\nL2 norm of t1, column-wise")
print(norm_t1)

hadamard(t1, t2)
tensor([[ 1.6883, -0.5295, -0.1082],
        [ 0.2456, -0.1172,  0.1633],
        [-0.5406, -0.9924, -0.8718],
        [-0.7028,  1.1492,  0.1529]])

Row-wise mean of t1
tensor([0.1157, 0.5168, 0.2591])
Row-wise standard deviation of t1
tensor([0.8466, 0.5062, 0.4616])

t1 . t2^T
tensor([[ 1.0506,  0.4588, -0.3220,  1.6383],
        [ 2.2614,  0.2917,  1.1906,  0.7552],
        [-1.0428,  0.8975, -2.4048,  1.0305],
        [-2.0881,  0.4203, -2.4684,  0.5993]])

t1^T . t2
tensor([[ 0.6905, -0.1437,  0.9784],
        [ 3.2590, -0.4899,  0.3353],
        [ 0.6947, -0.9848, -0.6637]])

L2 norm of t1, column-wise
tensor([1.1525, 0.9657, 1.1658, 1.1527])


In [10]:
# Split, stack, concat
t = torch.rand(6)
print(t)

# chunk allows us to break tensors into equal parts along a specific dimension "dim"
t_chunks = torch.chunk(t, chunks=3)
print("\nSplit into 3 chunks:")
print(t_chunks)

# split allows us to specify the exact size of the tensors to break into
t_splits = torch.split(t, split_size_or_sections=[4, 2])
print("\nSplit into a size 4 tensor and a size 2 tensor:")
print(t_splits)


# Concatenation:
A = torch.ones(3)
B = torch.zeros(3)
print("\nA and B:")
print(A)
print(B)

# Append row-wise
C = torch.cat([A, B], axis=0)
print("\nConcatenation of A and B along the row axis:")
print(C)

# Stack column-wise
Sc = torch.stack([A, B], axis=1)
# Stack row-wise
Sr = torch.stack([A, B], axis=0)

print("\nStacked column-wise:")
print(Sc)

print("\nStacked row-wise:")
print(Sr)

tensor([0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447])

Split into 3 chunks:
(tensor([0.6440, 0.7071]), tensor([0.6581, 0.4913]), tensor([0.8913, 0.1447]))

Split into a size 4 tensor and a size 2 tensor:
(tensor([0.6440, 0.7071, 0.6581, 0.4913]), tensor([0.8913, 0.1447]))

A and B:
tensor([1., 1., 1.])
tensor([0., 0., 0.])

Concatenation of A and B along the row axis:
tensor([1., 1., 1., 0., 0., 0.])

Stacked column-wise:
tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])

Stacked row-wise:
tensor([[1., 1., 1.],
        [0., 0., 0.]])
