In [2]:
import torch
import numpy as np

In [ ]:
# Creating tensors - this can be done with regular lists or transferred from numpy
a = [11, 33, 323]
b = np.array([44, 55, 66], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(t_a)
print(t_b)

tensor([ 11,  33, 323])
tensor([44, 55, 66], dtype=torch.int32)


In [10]:
# It is possible to use inbuilts to create tensors full of ones or zeros
# or random entries
t_ones = torch.ones(size=(2, 3))
print(t_ones.shape)
print(t_ones)

rand_tensor = torch.rand(size=(2, 3))
print(rand_tensor)

torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.8901, 0.4971, 0.4889],
        [0.3748, 0.4090, 0.4263]])


In [9]:
t_a_new = t_a.to(dtype=torch.int64)
print(t_a_new.dtype)

torch.int64
